USE [master]
GO

/****** Object:  Database [CSDL_QuanLyBanDoThoiTrang]    Script Date: 6/10/2019 1:28:17 PM ******/
DROP DATABASE [CSDL_QuanLyBanDoThoiTrang]
GO

/****** Object:  Database [CSDL_QuanLyBanDoThoiTrang]    Script Date: 6/10/2019 1:28:17 PM ******/
CREATE DATABASE [CSDL_QuanLyBanDoThoiTrang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CSDL_QuanLyBanGiay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CSDL_QuanLyBanGiay.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CSDL_QuanLyBanGiay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CSDL_QuanLyBanGiay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CSDL_QuanLyBanDoThoiTrang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ARITHABORT OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET RECOVERY FULL 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET  MULTI_USER 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CSDL_QuanLyBanDoThoiTrang] SET  READ_WRITE 
GO

